### ISSUE TITLE
API

### ISSUE THREAD

**Issue by deemidroll** [shri-2015-org/666#1]
запрос на логин "loginReq" 
{
  uid: uid
}

ответ на логин "loginRes"
{
  name: name,
  avatar: avatar,
  uid: uid
}

отправка сообщение "sendMessage"
{
  text: text,
  uid: uid
}

получение сообщения "message"
{
  text: text,
  uid: uid,
  time: time
}

получение данных другого юзера "getUser"
{
  name: name,
  avatar: avatar,
  uid: uid
}

**Comment by alt-j** [comment]
https://github.com/shri-2015-org/666/commit/81291ff50e320aa8f9eb859be8841db1a1b4f15f
