### ISSUE TITLE
Разбиение Navigation

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#103]
Компонент Navigation вырос до приличного размера, и явно просится разбить его на более мелкие.

Думаю, лучше всего сначала проработать ему дизайн, потому что он сейчас очень временный и сделан наспех. Потом, отталкиваться от дизайна.

**Comment by pofigizm** [comment]
Нужен дизайн @exah

**Comment by exah** [comment]
Что вы хотите от него видеть?
