### ISSUE TITLE
Приложение падает на некоторых ссылках (Opengraph)

### ISSUE THREAD

**Issue by exah** [shri-2015-org/666#131]
Например на: http://www.siteinspire.com

**Comment by tempname11** [comment]
Не понял, у тебя этот баг разрешился? Я у себя так и не смог воспроизвести.

**Comment by exah** [comment]
Да, если не было картинки ничего не возвращалось в компоненте, react это не любит. https://github.com/shri-2015-org/666/commit/a337e17af30d872c38555bbde0f14f7fef054193#diff-2940576e07b4a80b7c705b515165bdeeR27

**Comment by tempname11** [comment]
А, ты false возвращаешь. Понял.
