### ISSUE TITLE
Добпавить парочку OpenGraph plugins

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#135]
А то только один базовый -- это грустно. Можно, например, инлайн-видео c Youtube и инлайн-аудио с Soundcloud.

**Comment by pofigizm** [comment]
А у меня youtube работает...

**Comment by tempname11** [comment]
@Pofigizm это отрабатывает Generic, который показывает картинку и title. Он должен на всех OpenGraph документах работать (по http://ogp.me/ `Basic Metadata`)

А я имею в виду прямо рабочий ютюбовский плеер внутри чата.

**Comment by tempname11** [comment]
Youtube в #139 
На аудио не нашел подходящих сайтов почему-то. Soundcloud в OG не дает нормальных данных.

**Comment by tempname11** [comment]
Добавили Twitter =)
