### ISSUE TITLE
Роуты

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#136]
Должно быть не очень сложно с https://github.com/rackt/redux-router

Пока что видятся:

```
/
/welcome
/room/:roomID
```

**Comment by pofigizm** [comment]
А пустой это что?

**Comment by tempname11** [comment]
Хм, а действительно. Тогда `/welcome` не нужен, получается.

**Comment by deemidroll** [comment]
я сделаю серверную часть)

**Comment by tempname11** [comment]
Тут нет серверной части:)
