### ISSUE TITLE
Не работает выход из конфига по 'x'

### ISSUE THREAD

**Issue by petrukhin** [shri-2015-org/666#158]
Шаги для воспроизведения:
- Создаю комнату, комната появляется в боковом меню
- После этого нажимаю на 'x' рядом с названием комнаты - ничего не происходит 

В консоли:

```
Uncaught TypeError: undefined is not a function
```

UPD:

Связано с особенностью браузеров, http://babeljs.io/docs/usage/polyfill/ должен полечить

**Comment by tempname11** [comment]
https://github.com/shri-2015-org/666/pull/159
