### ISSUE TITLE
Подумать о документировании кода

### ISSUE THREAD

**Issue by mightyaleksey** [shri-2015-org/666#16]
JSDoc?

**Comment by alt-j** [comment]
https://github.com/shri-2015-org/666/issues/18

**Comment by megatolya** [comment]
У нас уже что-то есть про это https://github.com/shri-2015-org/666/wiki/API-server
@deemidroll актуальные доки?

**Comment by tempname11** [comment]
Завтра по поводу этого API постараюсь сделать PR

**Comment by deemidroll** [comment]
@megatolya  доки актуальные, но мы договорились, что откажемся от вики в пользу документирвоания непосредственно в коде. @tempname11 обещал показать, как :)
