### ISSUE TITLE
У сообщений из истории нет attachments

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#172]
Нету:(

**Comment by pofigizm** [comment]
Скучно? ))

**Comment by tempname11** [comment]
Не, просто в моих issues висели.

**Comment by naruzl** [comment]
Здорова мужики! Вы ещё фронтендите?

**Comment by tempname11** [comment]
Есть немного) а что?

**Comment by mightyaleksey** [comment]
случается иногда :)

**Comment by exah** [comment]
ага

**Comment by pofigizm** [comment]
типа всем надо отметиться )) ну тогда я тоже

**Comment by naruzl** [comment]
Молодцы! Это я так, чтобы посмотреть кто отреагирут ))

**Comment by naruzl** [comment]
Значит я один перешёл на другую сторону. Ну и ладно ))

**Comment by naruzl** [comment]
Всем привет! Расскажите, пожалуйста, каким образом вёрстку тестируете? Если вообще тестируете, может есть интересные решения?

**Comment by naruzl** [comment]
Может есть средства автоматизированного тестирования?

**Comment by megatolya** [comment]
я webdriver.io использую для функционального тестирования
