### ISSUE TITLE
jsdoc

### ISSUE THREAD

**Issue by naruzl** [shri-2015-org/666#18]
Добавить jsdoc

**Comment by deemidroll** [comment]
@alt-j  Вопрос: как лучше сделать общий jsdoc typedef для нескольких файлов, где он требуется?

**Comment by alt-j** [comment]
Достаточно описать в одном из файлов, удобнее всего в том, где этот формат генерируется.

**Comment by tempname11** [comment]
Задача слишком нечетко сформулирована.

**Comment by mightyaleksey** [comment]
Похоже дублирует: https://github.com/shri-2015-org/666/issues/16
