### ISSUE TITLE
Отказаться от использования gulp-тасок

### ISSUE THREAD

**Issue by alt-j** [shri-2015-org/666#23]
Можно посмотреть или в сторону `webpack-dev-server` или делать пересборку в middelware при запросе на статики (если у сборщика есть кеш).

**Comment by pofigizm** [comment]
В рамках этой задачи желательно добавить раздачу статики через наш сервер. Для дев окружения это будут файлы которые препроцессит webpack, а для прода это будут скомпиленые файлы.
