### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by deemidroll** [shri-2015-org/666#28]
Сделать сборщик standalone для мобильных и десктопов на phone gap и node-webkit

**Comment by megatolya** [comment]
Если сюда дойдет, советую начать с node-webkit. Phone gap тормозной, с кривым апи. Если захочется так уж упороться, то лучше пощупать react-native.

**Comment by deemidroll** [comment]
Уже щупаю, довольно приятно с ним работать

**Comment by deemidroll** [comment]
с react-native в смысле

**Comment by megatolya** [comment]
круто, расскажи потом, как он тебе

**Comment by mightyaleksey** [comment]
да, мне тоже интересно :)

**Comment by deemidroll** [comment]
Обязательно :)

**Comment by deemidroll** [comment]
удалось завести, но нужна помощь с redux, так как я его практически не понимаю, очень надеюсь завтра на вашу помощь :)
