### ISSUE TITLE
Завести VPS

### ISSUE THREAD

**Issue by deemidroll** [shri-2015-org/666#29]
Amazon или digital ocean, например.

**Comment by pofigizm** [comment]
DO
промокод `RADIO-T` - 10$

**Comment by pofigizm** [comment]
@deemidroll ты не против если я эту таску возьму на себя?

**Comment by pofigizm** [comment]
@deemidroll ping

**Comment by pofigizm** [comment]
да / нет ?

**Comment by deemidroll** [comment]
@Pofigizm да, конечно не против

**Comment by pofigizm** [comment]
ок
