### ISSUE TITLE
Сгруппировать CSS и JS для компонентов в одной папке

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#33]
По мотивам https://github.com/shri-2015-org/666/pull/32#issuecomment-139913870

@exah Нужно твое мнение, как автора всего существующего CSS

**Comment by tempname11** [comment]
@alt-j @sullenor меншн для нотификаций

**Comment by megatolya** [comment]
а не хотите [компоненты](https://github.com/shri-2015-org/666/tree/master/client/js/components) побить на папочки, например, [так](https://github.com/css-modules/webpack-demo/tree/master/src/components/0-Logo)?

**Comment by exah** [comment]
я за

**Comment by exah** [comment]
собираюсь так сделать, завтра / в субботу (в моей ветке локальной уже начал)
