### ISSUE TITLE
Учесть комментарии по поводу CSS 

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#35]
Табуляции и кодстайл -- https://github.com/shri-2015-org/666/pull/32#discussion-diff-39351304
Ручные префиксы -- https://github.com/shri-2015-org/666/pull/32#discussion-diff-39351322
Семантичная верстка -- https://github.com/shri-2015-org/666/pull/32#discussion_r39351374
SVGO -- https://github.com/shri-2015-org/666/pull/32#issuecomment-139912104

@alt-j @exah @sullenor

**Comment by exah** [comment]
1. Codestyle сторонних файлов тоже нужно править? Это типа как библиотека, во всех сорцах вы правите? (файл не для редактирования)
2. Некоторые префиксы убрал, но некоторые оставил (рассчитанные на специальные фичи браузеров (см. пункт 1 — это сторонний файл, не уверен, что это в принципе правильно)).
3. Насчет семантической вёрстки сильно сказано, но к этому участку кода не относится.
4. Да давай подключим svgo в gulp/webpack.

**Comment by mightyaleksey** [comment]
По хорошему, не нужно коммитить файлы сторонних библиотек в проект, либо коммитить все и игнорить.
