### ISSUE TITLE
Идея про проверку типов, а так же валидацию данных и API

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#36]
Оформлю это как рассказ о сегодняшнем эксперименте.
## Про пропсы:

Я решил немного поэкспериментировать с React-овским PropTypes. Для начала заметил, что propTypes очень плохо читаются и трудно пишутся:

``` js
PropTypes.arrayOf(
  PropTypes.shape({
    text: PropTypes.string.isRequired,
  }).isRequired).isRequired;
```

С помощью небольшой обертки я пришел к

``` js
ArrayOf(
  Shape({
    text: Str,
  })
)
```

Дальше, я заметил, что многие типа пропсов повторяются несколько раз (когда мы из внешнего React компонента пробрасываем их во внутренний, не изменяя).

Это привело меня к мысли своеобразных typedef-ов:

``` js
const MessagesT = ArrayOf(...);
```

Сначала я хотел писать typedef-ы в каком-то общем файле вроде types.js, но быстро понял что там будет каша при большом количестве типов. Само собой напрашивается определение типов именно в тех компонентах, где они нужны и экспорт их наружу.
## Про валидацию и API

Также мне пришла в голову мысль, что можно задействовать React-овский механизм проверки типов для произвольных данных. Вот как это может выглядеть:

``` js
const TransportMessageT = Shape({
  text: Str,
  uid: Str,
  time: Num,
});

const TransportUserT = Shape({
  avatar: Str,
  uid: Str,
  name: Str,
});

function onMessage(message) {
  ...
  assertType(message, TransportMessageT);
  ...
}

function onLoginRes(user) {
  ...
  assertType(user, TransportUserT);
  ...
}
```

Отсюда можно пойти дальше и определить эти типы данных в куске кода, общем для клиента и сервера. Тогда можно будет проверять их и на сервере, а API описывать в терминах этих typedef-ов.

Текущаа версия в ветке https://github.com/shri-2015-org/666/tree/feature-validation
Хотелось бы услышать ваши мысли -- стоит ли развивать ето направление.
@deemidroll @naruzl @Pofigizm
@alt-j @sullenor

**Comment by megatolya** [comment]
херасе

**Comment by pofigizm** [comment]
я думаю стоит, но параллельно с "продуктом", заранее все не предусмотриш

**Comment by tempname11** [comment]
@Pofigizm Тут нет задачи предусмотреть что-то, скорее просто более четко описать то, что есть:)

**Comment by tempname11** [comment]
@megatolya А можно поразвернутей?))) А то непонятно даже, положительная твоя реакция или отрицательная)

**Comment by megatolya** [comment]
:))
не, не, круто, конечно)

**Comment by mightyaleksey** [comment]
На мой взгляд эти проверки помогают на этапе разработки и гарантируют некоторую надежность приложения в будущем, чтобы не было такого: "Я вмержил ветку и у меня все сломалось :(". Да и проще становится вносить какие-то изменения (рефакторить).

Надежнее конечно писать тесты на API. Но как дешевая полумера - проверка типов тоже ок :)

**Comment by tempname11** [comment]
Надежнее делать и то, и другое:))

**Comment by tempname11** [comment]
Закрываю по причине того, что мы решили делать иначе. #49
