### ISSUE TITLE
Использовать Git-flow

### ISSUE THREAD

**Issue by exah** [shri-2015-org/666#37]
Предлогам перейти полностью на git-flow потому, что у нас и так, что-то типа этого и просиходит, только с git-flow будет всё более организованнее и по одной системе.

Базовые принципы 
- `master` - основная ветка
- `develop` - в разработке (можем пока не юзать, всё мёржить в мастер)
- Каждая фича разрабатывается в ветке `feature/foo`
- `hotfix/bar` быстрые фиксы для мастера тоже в отдельных ветках
- `release` можем не использовать (или делать после каждого шрикатона)

Есть специальная командная утилита: https://github.com/nvie/gitflow.

Пример использования:

```
git flow feature start <name>
# от develop отделяется ветка
git flow feature finish <name>
# мёрдж в develop
```

Либо просто заведем правило называть ветки по одной системе :innocent:

**Comment by exah** [comment]
Или я что-то пропустил и мы так и делаем?)

**Comment by pofigizm** [comment]
вроде так и делаем, только ветки называем `<username>.<feature>`

**Comment by exah** [comment]
а ещё `feature-<feature>`

**Comment by tempname11** [comment]
Поддерживаю git flow полностью. `develop` предлагаю начать юзать, когда у нас появится первая стабильная версия.

Ветки мне пока лично приятнее называть а-ля `feature-blah`. Андрей предлагал в субботу `username.#-featurename` (# -- номер issue), но такие имена оставляют небольшое ощущение тяжеловесности и бюрократичности, опять же чисто по личному ощущению:)

**Comment by tempname11** [comment]
Еще по поводу мерджей -- опять же по совету Андрея, давайте условимся, что pull-request в штатных ситуациях мы мерджим только тогда, когда двое (**2**) членов команды дали своё "+1". Это избавит нас от ситуации, когда в `develop` или `master` внезапно появляется код, который видит и понимает только один человек.

Правда, это будет означать, что на всех лежит ответственность стараться читать, вникать и комментировать чужой код. Но мне кажется, это хорошо.

Если мы принимаем эту систему, нужно ли нам принять какой-то символ для четкого обозначения этого "+1", чтобы не возникало неясных ситуаций, когда непонятно в точности, сколько человек дали согласие? Например, условиться писать именно "+1" в тексте комментария, а не, например "круто" или смайлики))

**Comment by deemidroll** [comment]
Ты говоришь, что имя в ветке - это бюрократия, но при этом хочешь четкому символ для подтверждения, что тогда уж тоже бюрократия)) Если серьезно то я за "ок" в качестве подтверждения и за имя в названии ветки.

**Comment by pofigizm** [comment]
имя в название ветки - [ок, +1] ))

**Comment by tempname11** [comment]
Ну, бюрократия это вроде когда приходится делать что-то потому, что "так положено" без понимания и принятия того, зачем. А я скорее за "давайте сами договоримся о том, что удобнее для нас".

**Comment by tempname11** [comment]
Все уже согласились, закрываю.
