### ISSUE TITLE
Frontend по дизайну окна чата

### ISSUE THREAD

**Issue by exah** [shri-2015-org/666#4]
![main window 2x](https://cloud.githubusercontent.com/assets/442932/9831520/6fd15498-5964-11e5-9eb5-eef1959502d2.png)
![main window copy 2x](https://cloud.githubusercontent.com/assets/442932/9831521/6ffabec8-5964-11e5-86d2-186d6a04ac57.png)

**Comment by megatolya** [comment]
лойс!
12 сент. 2015 г. 15:39 пользователь "exah" notifications@github.com
написал:

**Comment by megatolya** [comment]
PR вмерджен, закрываем?
