### ISSUE TITLE
Сделать легковесный transport builder

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#51]
Немного пересекается c #49

Notification,
Exchange на промисах.

**Comment by tempname11** [comment]
Совершенно непонятно стало, что делать с этим issue, когда @Pofigizm сделал PR с похожим функционалом #62.

@alt-j @sullenor требуется совет.

**Comment by alt-j** [comment]
Если pr полностью закрывает задачу, то, очевидно, закрываем.
Если большую часть задачи, то задачу можно переформулировать так, чтобы закрывал полностью, а на разницу завести отдельнную.
Если маленькую часть, то можно завести на эту маленькую часть отдельную задачу и просто связать их :)

**Comment by tempname11** [comment]
Закрываю, потому что идея слишком абстрактная и не стоит сейчас на ней фокусироваться. В случае необходимости можно будет открыть заново.
