### ISSUE TITLE
Умные action creator-ы

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#59]
см. https://github.com/shri-2015-org/666/pull/55#discussion_r39920788

**Comment by mightyaleksey** [comment]
Предлагаю сделать такую структуру:
- Непосредственно в рамках компонента Room (который описывает структуру комнаты) связать MessageList и RoomInput через connect из redux с состоянием приложения:
  - MessageList связывается со списком сообщений (явно передаем через connect).
  - RoomInput связываем с пользовательским вводом (userInput), который храним в сторе.
  - в рамках RoomInput подписываться на изменения input через onChange и диспатчить новое состояние
  - в рамках RoomInput обрабатываем клик по кнопке и диспатчим добавление сообщения и вызывать транспорт (из модуля)

Бонусы:
- У нас уходит необходимость тащить обработчик добавления сообщений с самых верхов приложения
- Кнопку можно научить по userInput'у менять свое состояние (disabled)

**Comment by tempname11** [comment]
А-а-а, отжали issue 🙀

**Comment by tempname11** [comment]
@sullenor да, мне нравится. если правильно понимаю, заодно избавимся от мутаций DOM-а а-ля `findDOMNode(...).value = ''` (для поля ввода)

**Comment by mightyaleksey** [comment]
@tempname11 Сережа начал работу и хотел довести до ума ее :)
И да, избавимся от прямой работы с DOM-нодами :)

Предлагаю, потом еще разок на ревью посмотреть вместе )

**Comment by mightyaleksey** [comment]
@tempname11 Как вариант, ты можешь попробовать доработать функцию reducer и избавить обработку каждого экшена в виде `switch case`. А входные данные описать в виде объекта:

``` javascript
{
  [ADD]: addFunction,
  // ...
}
```

**Comment by pofigizm** [comment]
>  {
>        [ADD]: addFunction,
>        // ...
>  }

+1

**Comment by tempname11** [comment]
Закрываю, как не решающую никаких непосредственных проблем тему. Как именно можно переструктурировать код, понятно, и в случае возникшей необходимости я смогу это сделать.
