### ISSUE TITLE
RFC (Request For Comment) по теме API

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#64]
Пытаюсь сделать #49. Нужны комментарии, как общие, так и по темам, отмеченным в коде как №1 №2, №3

@deemidroll @Pofigizm @khokhlachev @naruzl 
@alt-j @sullenor 
### common/transport/api.js

``` js
import User from '../../User'
import Message from '../../Message'

export const UP = 'UP';
export const DOWN = 'DOWN';
// №1: Как описать Direction в терминах jsdoc?
// Он может принимать значения UP или DOWN

/**
 * @class
 * @this {LoginRequest}
 * @param {string} uid
 */
export class LoginRequest {
  constructor(uid) { // TODO Проверить валидность
    this.uid = uid;
  }
}

/**
 * @class
 * @this {MiniMessage} // №2 -- какое лучше выбрать имя?
 * @param {string} uid
 * @param {string} text
 */
export class MiniMessage {
  constructor(uid, text) { // TODO Проверить валидность
    this.uid = uid;
    this.text = text;
  }
}

/**
 * @class
 * @this {Exchange}
 * @param {Direction} initialDirection
 * @param {Type} requestType
 * @param {Type} replyType
 */
export class Exchange {
  constructor(initialDirection, requestType, replyType) {
    this.initialDirection = initialDirection;
    this.requestType = requestType;
    this.replyType = replyType;
  }
}

export default {
  newUser:   Notification(DOWN, User);
  login:     Exchange(UP, LoginRequest, User),
  message:   Exchange(UP, MiniMessage, Message),
  read:      Exchange(UP, Message, Message),
  userInfo:  Exchange(UP, User, User),

  roomUsers: Exchange(UP, undefined, Users),
  // №3: как лучше выразить, что в запросе нет данных?
}
```

**Comment by deemidroll** [comment]
@tempname11, мы обсуждали \* @this в jsdoc'ах, он все-таки нужен? Ты хочешь отправлять на сервер MiniMessage вместе Message? Может все-таки слать полноценный Message, тем более, что сейчас message id ставит клиент, да и время отправки можено проставлять на клиенте, так как оно required в конструкторе Message, а на сервере обновлять. Раз уж мы хотим использовать конструкторы Message и User как на сервере так и на клиенте.

**Comment by tempname11** [comment]
@deemidroll я просто написал так, как есть в вики. Там двух полей не хватает. Но я не против использовать обычный Message

**Comment by tempname11** [comment]
@deemidroll про this -- а как ты предлагаешь?

**Comment by deemidroll** [comment]
@tempname11 "@this" используем в jsdoc'ах только методов, а не конструкторов

**Comment by tempname11** [comment]
То есть просто стереть строчку с this, верно?

**Comment by mightyaleksey** [comment]
На мой взгляд `@this` для классов не имеет смысла. Для функции - да, так как там контекст вызова может быть разный (и то это плохой кейс использования и лучше так не делать).

Константы можно описать просто через `@type`: http://usejsdoc.org/tags-type.html

**Comment by deemidroll** [comment]
@tempname11 

> То есть просто стереть строчку с this, верно? 

да :)

**Comment by tempname11** [comment]
@sullenor Не вижу по ссылке, как type помогает.

Может быть, http://usejsdoc.org/tags-enum.html ?

**Comment by mightyaleksey** [comment]
@tempname11 Я не очень понял, что у тебя вызывает трудности: описать тип переменной или экспорты? Или нужно соответствующее название придумать?

**Comment by tempname11** [comment]
@sullenor я хочу написать какое-то описание того факта, что значение -- в точности UP или DOWN и ни что иное.

**Comment by mightyaleksey** [comment]
@tempname11 мне кажется, что названия UP и DOWN звучат очень абстрактно и неочень понятно из названия переменной, что ты имел ввиду.

**Comment by alt-j** [comment]
- по поводу `this`, рьяно поддерживаю Лешу
- по поводу direction, я бы сделал константу `DATA_DIRECTION`, `@enum {String}`

**Comment by alt-j** [comment]
№3:
- зачем в Exchange передавать requestType?
- в конструкторе `Exchange` тип `requestType` может принимать undefined, это тоже стоит выразить в jsdoc
- `{Type}` непонятный тип данных, или надо завести такой класс (хотя непонятно зачем он нужен), или писать `Object`
- в конструкторах хорошей практикой считается еще минимально описывать ответственность компонента, тоже самое можно делать для непонятных параметров

**Comment by tempname11** [comment]
Закрываю как непродуктивную тему.
