### ISSUE TITLE
Реализация комнат (сервер)

### ISSUE THREAD

**Issue by mightyaleksey** [shri-2015-org/666#7]
- Протухание комнаты (нет никого)
- Возможность получение списка пользователей для конкретной комнаты
- Добавление комнат

**Comment by naruzl** [comment]
Наверное, необходимо будет добавить возможность как захода в комнату, так и возможность выхода из нее. Если все вышли, комната автоматически закрывается, чтобы не висели пустые.

**Comment by tempname11** [comment]
Да, причем выход не по закрытию вкладки браузера, а именно UI-шное действие пользователя. А то будет неудобно очень.
