### ISSUE TITLE
Поддержка markdown

### ISSUE THREAD

**Issue by pofigizm** [shri-2015-org/666#91]

**Comment by exah** [comment]
Markdown должен рендерится на сервере или на клиенте?

**Comment by exah** [comment]
На клиенте он сразу увидит своё сообщение отформатированным, а если на сервере будет меньше нагрузки на клиент...

**Comment by tempname11** [comment]
На клиенте, конечно. Живое превью можно сделать будет.

**Comment by tempname11** [comment]
Предлагаю использовать https://github.com/chjj/marked

**Comment by exah** [comment]
@tempname11 ну понятно, что marked :) Про живое превью не вариант, он же заменяет символы `md` на `html` теги, я это в `textarea` не сделаю, нужен тогда делать сплит редактор / превью.

**Comment by pofigizm** [comment]
Да нет, набираешь в маркдауне -> хранится / отправляется на сервер / приходит с сервера в маркдауне -> отображается в html

**Comment by exah** [comment]
@Pofigizm ок

**Comment by tempname11** [comment]
@exah да, я имел в виду отдельно стоящее превью. Может быть так, что ты начинаешь писать сообщение, а в MessageList появляется твоё живое сообщение-превью? На другом фоне или еще как-то визуально отделенное от "настоящих сообщений". И когда нажимаешь энтер, то оно просто меняет стиль на обычный.

**Comment by exah** [comment]
@tempname11 Предлагаю делать это не сразу))

**Comment by tempname11** [comment]
@exah ну вообще если сконцентрироваться то это задачка на час. Завтра разберемся)
