### ISSUE TITLE
Баг: возможно послать joinRoom несколько раз подряд.

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#94]
Сервер отвечает на каждый из этих запросов и создает несколько новых пользователей. Мне кажется, очевидно, что после первого успешного запроса нужно начинать выдавать ошибки.

**Comment by pofigizm** [comment]
Решится в рамках "ReJoinRoom"

**Comment by pofigizm** [comment]
Клиенская часть в задаче #84

**Comment by tempname11** [comment]
Не очень актуально, поскольку сервер переписывается по-новому @deemidroll. Когда это будет сделано, нужно обратить внимание, корректно ли новый сервер обрабатывает эту ситуацию.
