### ISSUE TITLE
Переименовать файлы компонентов

### ISSUE THREAD

**Issue by tempname11** [shri-2015-org/666#97]
Вместо структуры:

```
- Room
----- Room.js
----- Room.scss
- RoomInput
----- RoomInput.js
----- RoomInput.scss
```

cделать

```
- Room
----- index.js
----- index.scss
- RoomInput
----- index.js
----- index.scss
```

Тогда становятся проще импорты:

Вместо
`import RoomInput from '../RoomInput/RoomInput'
будет
`import RoomInput from '../RoomInput'

См. https://github.com/sullenor/todos/blob/master/components/app/index.js

**Comment by pofigizm** [comment]
Также внутри тупых компонент достаточно

```
export default class extends Component {
```

**Comment by pofigizm** [comment]
:+1:
